[package]
name = "da-sender"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.0"
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
serde_json = "1.0.116"
tokio = { version = "1", features = ["full"] }
