version: '3.8'

services:
  avail-da-node:
    build:
      context: ./avail-da-node
      dockerfile: Dockerfile
    ports:
      - "9944:9944"

  avail-light-bootstrap:
    build:
      context: ./avail-light-bootstrap
      dockerfile: Dockerfile
    ports:
      - "39000:39000"
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  avail-light:
    build:
      context: ./avail-light
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command:
      sh -c "./wait_for_node.sh"
    depends_on:
      - avail-da-node

  avail-da-server:
    build:
      context: ./avail-da-server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
