http_server_host = '127.0.0.1'
http_server_port = 8000
port = 38000
tcp_port_reuse = false
autonat_only_global_ips = false
autonat_throttle = 1
autonat_retry_interval = 10
autonat_refresh_interval = 30
autonat_boot_delay = 5
identify_protocol = '/avail_kad/id/1.0.0'
identify_agent = 'avail-light-client/rust-client'
bootstraps=['/dns/bootnode.2.lightclient.goldberg.avail.tools/tcp/37000/p2p/12D3KooWRCgfvaLSnQfkwGehrhSNpY7i5RenWKL2ARst6ZqgdZZd','/dns/bootnode.1.lightclient.goldberg.avail.tools/tcp/37000/p2p/12D3KooWBkLsNGaD3SpMaRWtAmWVuiZg1afdNSPbtJ8M8r9ArGRT']
bootstrap_period = 300
relays = []
full_node_ws=['wss://rpc-testnet.avail.tools/ws','wss://avail-goldberg-rpc.lgns.xyz:443/ws','wss://rpc-goldberg.sandbox.avail.tools:443','wss://avail-goldberg.public.blastapi.io:443','wss://lc-rpc-goldberg.avail.tools:443/ws']
confidence = 92.0
avail_path = 'avail_path'
log_level = 'INFO'
log_format_json = false
ot_collector_endpoint = 'http://otelcollector.avail.tools:4317'
disable_rpc = false
disable_proof_verification = false
dht_parallelization_limit = 20
put_batch_size = 1000
query_proof_rpc_parallel_tasks = 8
max_cells_per_rpc = 30
threshold = 5000
kad_record_ttl = 86400
publication_interval = 43200
replication_interval = 10800
replication_factor = 20
connection_idle_timeout = 30
query_timeout = 60
query_parallelism = 3
caching_max_peers = 1
disjoint_query_paths = false
max_kad_record_number = 2400000
max_kad_record_size = 8192
max_kad_provided_keys = 1024
app_id=1
