name: Deno Check Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Use Deno Version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Lint Deno Module
        run: cd deno && deno fmt --check
