name: Deno Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2
      - name: Set up .env
        run: |
            echo ${{ secrets.ENV}} >> deno/.env
      - name: Use Deno Version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Run tests
        run: |
          cd deno && deno task test
