name: Rustfmt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@1.76
        with:
          components: rustfmt

      - name: Run rustfmt da-sender
        run: cd da-sender && cargo fmt --all -- --check

      - name: Run rustfmt da-getter
        run: cd da-getter && cargo fmt --all -- --check
